FROM node:18-alpine

WORKDIR /app

COPY miniapp/package*.json ./
RUN npm install

COPY miniapp/ ./

RUN npm run build

EXPOSE 3000

# --cors разрешает все origins, -L разрешает все хосты
CMD ["npx", "serve", "-s", "dist", "-l", "3000", "--cors", "-L"]

